### ISSUE TITLE
Fix Travis and add Codecov

### ISSUE THREAD

**Issue by theodesp** [theodesp/go-heaps#21]

**Comment by DonMcNamara** [comment]
I think the person doing this would need admin rights on the repo.

```
You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.
```

**Comment by theodesp** [comment]
When you fork you can also run the tests in your own repo.

**Comment by DonMcNamara** [comment]
Ahh, good point.

**Comment by DonMcNamara** [comment]
I opened a PR for this. Let me know what you think. I think it is a decent start, but could be cleaner.

**Comment by theodesp** [comment]
Ta!
