### ISSUE TITLE
Add Rank pairing heap implementation

### ISSUE THREAD

**Issue by theodesp** [theodesp/go-heaps#9]
http://www.cs.princeton.edu/courses/archive/spr10/cos423/handouts/rankpairingheaps.pdf
http://www.cs.princeton.edu/courses/archive/spr11/cos423/Lectures/RankPairingHeaps.pdf
https://github.com/shingyipcheung/rank-pairing-heaps

**Comment by erjiaqing** [comment]
I'd like to take this.

**Comment by theodesp** [comment]
Cool!
